@startwbs
* Data Types in Java
** Primitive
*** Numeric
****< Integral (Real Number)
*****< Integer
****** byte
****** short
****** int
****** long
***** Floating-Point
****** float
****** double
**** Character
***** Char
***< Boolean
**** Boolean
** Non-Primitive (Reference)
*** String
*** Array
*** etc.
@endwbs