@startuml
class Person {
    - String name
    - int age
    + Person()
    + Person(String name, int age)
    + void show()
}

class Student {
    - String department
    + Student()
    + Student(String name, int age, String dep)
}

Person <|-- Student
    
@enduml